package com.example.myandroidproject.util

const val ACCESS_FINE_LOCATION_PERMISSION_REQUEST_CODE = 100
const val ACCESS_COARSE_LOCATION_PERMISSION_REQUEST_CODE = 101
const val PHONE_STATE_PERMISSION_REQUEST = 102
const val CAMERA_PERMISSION_REQUEST_CODE = 103
